// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: proto/glambdar.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InvokeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FuncName      string                 `protobuf:"bytes,1,opt,name=func_name,json=funcName,proto3" json:"func_name,omitempty"`
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          []byte                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeRequest) Reset() {
	*x = InvokeRequest{}
	mi := &file_proto_glambdar_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeRequest) ProtoMessage() {}

func (x *InvokeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_glambdar_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeRequest.ProtoReflect.Descriptor instead.
func (*InvokeRequest) Descriptor() ([]byte, []int) {
	return file_proto_glambdar_proto_rawDescGZIP(), []int{0}
}

func (x *InvokeRequest) GetFuncName() string {
	if x != nil {
		return x.FuncName
	}
	return ""
}

func (x *InvokeRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *InvokeRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *InvokeRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type InvokeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          []byte                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	ColdStart     bool                   `protobuf:"varint,4,opt,name=cold_start,json=coldStart,proto3" json:"cold_start,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeResponse) Reset() {
	*x = InvokeResponse{}
	mi := &file_proto_glambdar_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeResponse) ProtoMessage() {}

func (x *InvokeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_glambdar_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeResponse.ProtoReflect.Descriptor instead.
func (*InvokeResponse) Descriptor() ([]byte, []int) {
	return file_proto_glambdar_proto_rawDescGZIP(), []int{1}
}

func (x *InvokeResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *InvokeResponse) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *InvokeResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *InvokeResponse) GetColdStart() bool {
	if x != nil {
		return x.ColdStart
	}
	return false
}

type PreloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FuncName      string                 `protobuf:"bytes,1,opt,name=func_name,json=funcName,proto3" json:"func_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreloadRequest) Reset() {
	*x = PreloadRequest{}
	mi := &file_proto_glambdar_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreloadRequest) ProtoMessage() {}

func (x *PreloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_glambdar_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreloadRequest.ProtoReflect.Descriptor instead.
func (*PreloadRequest) Descriptor() ([]byte, []int) {
	return file_proto_glambdar_proto_rawDescGZIP(), []int{2}
}

func (x *PreloadRequest) GetFuncName() string {
	if x != nil {
		return x.FuncName
	}
	return ""
}

type PreloadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreloadResponse) Reset() {
	*x = PreloadResponse{}
	mi := &file_proto_glambdar_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreloadResponse) ProtoMessage() {}

func (x *PreloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_glambdar_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreloadResponse.ProtoReflect.Descriptor instead.
func (*PreloadResponse) Descriptor() ([]byte, []int) {
	return file_proto_glambdar_proto_rawDescGZIP(), []int{3}
}

func (x *PreloadResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PreloadResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type EvictRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FuncName      string                 `protobuf:"bytes,1,opt,name=func_name,json=funcName,proto3" json:"func_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvictRequest) Reset() {
	*x = EvictRequest{}
	mi := &file_proto_glambdar_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvictRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvictRequest) ProtoMessage() {}

func (x *EvictRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_glambdar_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvictRequest.ProtoReflect.Descriptor instead.
func (*EvictRequest) Descriptor() ([]byte, []int) {
	return file_proto_glambdar_proto_rawDescGZIP(), []int{4}
}

func (x *EvictRequest) GetFuncName() string {
	if x != nil {
		return x.FuncName
	}
	return ""
}

type EvictResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvictResponse) Reset() {
	*x = EvictResponse{}
	mi := &file_proto_glambdar_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvictResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvictResponse) ProtoMessage() {}

func (x *EvictResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_glambdar_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvictResponse.ProtoReflect.Descriptor instead.
func (*EvictResponse) Descriptor() ([]byte, []int) {
	return file_proto_glambdar_proto_rawDescGZIP(), []int{5}
}

func (x *EvictResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_proto_glambdar_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_glambdar_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_glambdar_proto_rawDescGZIP(), []int{6}
}

type StatusResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NodeId          string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Pools           map[string]*PoolStatus `protobuf:"bytes,2,rep,name=pools,proto3" json:"pools,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CpuAvailable    float64                `protobuf:"fixed64,3,opt,name=cpu_available,json=cpuAvailable,proto3" json:"cpu_available,omitempty"`
	MemoryAvailable int64                  `protobuf:"varint,4,opt,name=memory_available,json=memoryAvailable,proto3" json:"memory_available,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_proto_glambdar_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_glambdar_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_glambdar_proto_rawDescGZIP(), []int{7}
}

func (x *StatusResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *StatusResponse) GetPools() map[string]*PoolStatus {
	if x != nil {
		return x.Pools
	}
	return nil
}

func (x *StatusResponse) GetCpuAvailable() float64 {
	if x != nil {
		return x.CpuAvailable
	}
	return 0
}

func (x *StatusResponse) GetMemoryAvailable() int64 {
	if x != nil {
		return x.MemoryAvailable
	}
	return 0
}

type PoolStatus struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IdleCount      int32                  `protobuf:"varint,1,opt,name=idle_count,json=idleCount,proto3" json:"idle_count,omitempty"`
	ActiveCount    int32                  `protobuf:"varint,2,opt,name=active_count,json=activeCount,proto3" json:"active_count,omitempty"`
	MaxConcurrency int32                  `protobuf:"varint,3,opt,name=max_concurrency,json=maxConcurrency,proto3" json:"max_concurrency,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PoolStatus) Reset() {
	*x = PoolStatus{}
	mi := &file_proto_glambdar_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PoolStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoolStatus) ProtoMessage() {}

func (x *PoolStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_glambdar_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoolStatus.ProtoReflect.Descriptor instead.
func (*PoolStatus) Descriptor() ([]byte, []int) {
	return file_proto_glambdar_proto_rawDescGZIP(), []int{8}
}

func (x *PoolStatus) GetIdleCount() int32 {
	if x != nil {
		return x.IdleCount
	}
	return 0
}

func (x *PoolStatus) GetActiveCount() int32 {
	if x != nil {
		return x.ActiveCount
	}
	return 0
}

func (x *PoolStatus) GetMaxConcurrency() int32 {
	if x != nil {
		return x.MaxConcurrency
	}
	return 0
}

var File_proto_glambdar_proto protoreflect.FileDescriptor

const file_proto_glambdar_proto_rawDesc = "" +
	"\n" +
	"\x14proto/glambdar.proto\x12\bglambdar\"\xd4\x01\n" +
	"\rInvokeRequest\x12\x1b\n" +
	"\tfunc_name\x18\x01 \x01(\tR\bfuncName\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12>\n" +
	"\aheaders\x18\x03 \x03(\v2$.glambdar.InvokeRequest.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x04 \x01(\fR\x04body\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe1\x01\n" +
	"\x0eInvokeResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12?\n" +
	"\aheaders\x18\x02 \x03(\v2%.glambdar.InvokeResponse.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x03 \x01(\fR\x04body\x12\x1d\n" +
	"\n" +
	"cold_start\x18\x04 \x01(\bR\tcoldStart\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"-\n" +
	"\x0ePreloadRequest\x12\x1b\n" +
	"\tfunc_name\x18\x01 \x01(\tR\bfuncName\"E\n" +
	"\x0fPreloadResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"+\n" +
	"\fEvictRequest\x12\x1b\n" +
	"\tfunc_name\x18\x01 \x01(\tR\bfuncName\")\n" +
	"\rEvictResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x0f\n" +
	"\rStatusRequest\"\x84\x02\n" +
	"\x0eStatusResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x129\n" +
	"\x05pools\x18\x02 \x03(\v2#.glambdar.StatusResponse.PoolsEntryR\x05pools\x12#\n" +
	"\rcpu_available\x18\x03 \x01(\x01R\fcpuAvailable\x12)\n" +
	"\x10memory_available\x18\x04 \x01(\x03R\x0fmemoryAvailable\x1aN\n" +
	"\n" +
	"PoolsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.glambdar.PoolStatusR\x05value:\x028\x01\"w\n" +
	"\n" +
	"PoolStatus\x12\x1d\n" +
	"\n" +
	"idle_count\x18\x01 \x01(\x05R\tidleCount\x12!\n" +
	"\factive_count\x18\x02 \x01(\x05R\vactiveCount\x12'\n" +
	"\x0fmax_concurrency\x18\x03 \x01(\x05R\x0emaxConcurrency2\x96\x02\n" +
	"\rGlambdarAgent\x12;\n" +
	"\x06Invoke\x12\x17.glambdar.InvokeRequest\x1a\x18.glambdar.InvokeResponse\x12F\n" +
	"\x0fPreloadFunction\x12\x18.glambdar.PreloadRequest\x1a\x19.glambdar.PreloadResponse\x12@\n" +
	"\rEvictFunction\x12\x16.glambdar.EvictRequest\x1a\x17.glambdar.EvictResponse\x12>\n" +
	"\tGetStatus\x12\x17.glambdar.StatusRequest\x1a\x18.glambdar.StatusResponseB)Z'github.com/eswar-7116/glambdar/v3/protob\x06proto3"

var (
	file_proto_glambdar_proto_rawDescOnce sync.Once
	file_proto_glambdar_proto_rawDescData []byte
)

func file_proto_glambdar_proto_rawDescGZIP() []byte {
	file_proto_glambdar_proto_rawDescOnce.Do(func() {
		file_proto_glambdar_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_glambdar_proto_rawDesc), len(file_proto_glambdar_proto_rawDesc)))
	})
	return file_proto_glambdar_proto_rawDescData
}

var file_proto_glambdar_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_glambdar_proto_goTypes = []any{
	(*InvokeRequest)(nil),   // 0: glambdar.InvokeRequest
	(*InvokeResponse)(nil),  // 1: glambdar.InvokeResponse
	(*PreloadRequest)(nil),  // 2: glambdar.PreloadRequest
	(*PreloadResponse)(nil), // 3: glambdar.PreloadResponse
	(*EvictRequest)(nil),    // 4: glambdar.EvictRequest
	(*EvictResponse)(nil),   // 5: glambdar.EvictResponse
	(*StatusRequest)(nil),   // 6: glambdar.StatusRequest
	(*StatusResponse)(nil),  // 7: glambdar.StatusResponse
	(*PoolStatus)(nil),      // 8: glambdar.PoolStatus
	nil,                     // 9: glambdar.InvokeRequest.HeadersEntry
	nil,                     // 10: glambdar.InvokeResponse.HeadersEntry
	nil,                     // 11: glambdar.StatusResponse.PoolsEntry
}
var file_proto_glambdar_proto_depIdxs = []int32{
	9,  // 0: glambdar.InvokeRequest.headers:type_name -> glambdar.InvokeRequest.HeadersEntry
	10, // 1: glambdar.InvokeResponse.headers:type_name -> glambdar.InvokeResponse.HeadersEntry
	11, // 2: glambdar.StatusResponse.pools:type_name -> glambdar.StatusResponse.PoolsEntry
	8,  // 3: glambdar.StatusResponse.PoolsEntry.value:type_name -> glambdar.PoolStatus
	0,  // 4: glambdar.GlambdarAgent.Invoke:input_type -> glambdar.InvokeRequest
	2,  // 5: glambdar.GlambdarAgent.PreloadFunction:input_type -> glambdar.PreloadRequest
	4,  // 6: glambdar.GlambdarAgent.EvictFunction:input_type -> glambdar.EvictRequest
	6,  // 7: glambdar.GlambdarAgent.GetStatus:input_type -> glambdar.StatusRequest
	1,  // 8: glambdar.GlambdarAgent.Invoke:output_type -> glambdar.InvokeResponse
	3,  // 9: glambdar.GlambdarAgent.PreloadFunction:output_type -> glambdar.PreloadResponse
	5,  // 10: glambdar.GlambdarAgent.EvictFunction:output_type -> glambdar.EvictResponse
	7,  // 11: glambdar.GlambdarAgent.GetStatus:output_type -> glambdar.StatusResponse
	8,  // [8:12] is the sub-list for method output_type
	4,  // [4:8] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_glambdar_proto_init() }
func file_proto_glambdar_proto_init() {
	if File_proto_glambdar_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_glambdar_proto_rawDesc), len(file_proto_glambdar_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_glambdar_proto_goTypes,
		DependencyIndexes: file_proto_glambdar_proto_depIdxs,
		MessageInfos:      file_proto_glambdar_proto_msgTypes,
	}.Build()
	File_proto_glambdar_proto = out.File
	file_proto_glambdar_proto_goTypes = nil
	file_proto_glambdar_proto_depIdxs = nil
}
