// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.1
// source: proto/glambdar.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GlambdarAgent_Invoke_FullMethodName          = "/glambdar.GlambdarAgent/Invoke"
	GlambdarAgent_PreloadFunction_FullMethodName = "/glambdar.GlambdarAgent/PreloadFunction"
	GlambdarAgent_EvictFunction_FullMethodName   = "/glambdar.GlambdarAgent/EvictFunction"
	GlambdarAgent_GetStatus_FullMethodName       = "/glambdar.GlambdarAgent/GetStatus"
)

// GlambdarAgentClient is the client API for GlambdarAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GlambdarAgentClient interface {
	Invoke(ctx context.Context, in *InvokeRequest, opts ...grpc.CallOption) (*InvokeResponse, error)
	PreloadFunction(ctx context.Context, in *PreloadRequest, opts ...grpc.CallOption) (*PreloadResponse, error)
	EvictFunction(ctx context.Context, in *EvictRequest, opts ...grpc.CallOption) (*EvictResponse, error)
	GetStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
}

type glambdarAgentClient struct {
	cc grpc.ClientConnInterface
}

func NewGlambdarAgentClient(cc grpc.ClientConnInterface) GlambdarAgentClient {
	return &glambdarAgentClient{cc}
}

func (c *glambdarAgentClient) Invoke(ctx context.Context, in *InvokeRequest, opts ...grpc.CallOption) (*InvokeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InvokeResponse)
	err := c.cc.Invoke(ctx, GlambdarAgent_Invoke_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *glambdarAgentClient) PreloadFunction(ctx context.Context, in *PreloadRequest, opts ...grpc.CallOption) (*PreloadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PreloadResponse)
	err := c.cc.Invoke(ctx, GlambdarAgent_PreloadFunction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *glambdarAgentClient) EvictFunction(ctx context.Context, in *EvictRequest, opts ...grpc.CallOption) (*EvictResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EvictResponse)
	err := c.cc.Invoke(ctx, GlambdarAgent_EvictFunction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *glambdarAgentClient) GetStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, GlambdarAgent_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GlambdarAgentServer is the server API for GlambdarAgent service.
// All implementations must embed UnimplementedGlambdarAgentServer
// for forward compatibility.
type GlambdarAgentServer interface {
	Invoke(context.Context, *InvokeRequest) (*InvokeResponse, error)
	PreloadFunction(context.Context, *PreloadRequest) (*PreloadResponse, error)
	EvictFunction(context.Context, *EvictRequest) (*EvictResponse, error)
	GetStatus(context.Context, *StatusRequest) (*StatusResponse, error)
	mustEmbedUnimplementedGlambdarAgentServer()
}

// UnimplementedGlambdarAgentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGlambdarAgentServer struct{}

func (UnimplementedGlambdarAgentServer) Invoke(context.Context, *InvokeRequest) (*InvokeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Invoke not implemented")
}
func (UnimplementedGlambdarAgentServer) PreloadFunction(context.Context, *PreloadRequest) (*PreloadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PreloadFunction not implemented")
}
func (UnimplementedGlambdarAgentServer) EvictFunction(context.Context, *EvictRequest) (*EvictResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EvictFunction not implemented")
}
func (UnimplementedGlambdarAgentServer) GetStatus(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedGlambdarAgentServer) mustEmbedUnimplementedGlambdarAgentServer() {}
func (UnimplementedGlambdarAgentServer) testEmbeddedByValue()                       {}

// UnsafeGlambdarAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GlambdarAgentServer will
// result in compilation errors.
type UnsafeGlambdarAgentServer interface {
	mustEmbedUnimplementedGlambdarAgentServer()
}

func RegisterGlambdarAgentServer(s grpc.ServiceRegistrar, srv GlambdarAgentServer) {
	// If the following call panics, it indicates UnimplementedGlambdarAgentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GlambdarAgent_ServiceDesc, srv)
}

func _GlambdarAgent_Invoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvokeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GlambdarAgentServer).Invoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GlambdarAgent_Invoke_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GlambdarAgentServer).Invoke(ctx, req.(*InvokeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GlambdarAgent_PreloadFunction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PreloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GlambdarAgentServer).PreloadFunction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GlambdarAgent_PreloadFunction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GlambdarAgentServer).PreloadFunction(ctx, req.(*PreloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GlambdarAgent_EvictFunction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EvictRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GlambdarAgentServer).EvictFunction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GlambdarAgent_EvictFunction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GlambdarAgentServer).EvictFunction(ctx, req.(*EvictRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GlambdarAgent_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GlambdarAgentServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GlambdarAgent_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GlambdarAgentServer).GetStatus(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GlambdarAgent_ServiceDesc is the grpc.ServiceDesc for GlambdarAgent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GlambdarAgent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "glambdar.GlambdarAgent",
	HandlerType: (*GlambdarAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Invoke",
			Handler:    _GlambdarAgent_Invoke_Handler,
		},
		{
			MethodName: "PreloadFunction",
			Handler:    _GlambdarAgent_PreloadFunction_Handler,
		},
		{
			MethodName: "EvictFunction",
			Handler:    _GlambdarAgent_EvictFunction_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _GlambdarAgent_GetStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/glambdar.proto",
}
